// @vitest-environment node
import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { TYPERT } from 'dsh-plugin-shop/typert'
import TYPERT_REMOTE from 'dsh-plugin-shop/remote'
import { DUAL_CODEC_MARKER, withCreateFactories } from '../scripts/typert-dual-codecs.ts'

/** A host face shaped exactly as dsh-typert-generator 0.1.1-rc.2 prints one
 * (`emitter.js`: `strictCodec()` for every codec, one `{ name, schema }` line
 * per named schema): a named schema, a Context receiver codec, a parameter
 * codec and a result codec. */
const GENERATED = [
  '/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */',
  "import { z } from 'zod'",
  '',
  'const a$schema = z.string()',
  'const b$schema = z.object({',
  "  'schema': z.string(),",
  '})',
  'const c$schema = z.number()',
  '',
  'export const TYPERT = {',
  "  package: 'demo',",
  "  face: 'host',",
  '  schemas: [',
  "    { name: 'Named', schema: a$schema },",
  '  ],',
  '  invocations: [',
  '    {',
  "      id: 'demo#svc/run',",
  '      invocation: {',
  "        kind: 'context',",
  '        codec: {',
  "          mode: 'strict',",
  "          typeSymbol: 'demo#svc/run:context',",
  '          schema: a$schema,',
  '        },',
  '      },',
  '      parameters: [',
  '        {',
  "          name: 'args',",
  '          codec: {',
  "            mode: 'strict',",
  "            typeSymbol: 'demo#svc/run:args',",
  '            schema: b$schema,',
  '          },',
  '        },',
  '      ],',
  '      result: {',
  "        mode: 'strict',",
  "        typeSymbol: 'demo#svc/run:result',",
  '        schema: c$schema,',
  '      },',
  '    },',
  '  ],',
  '}',
  '',
].join('\n')

describe('withCreateFactories', () => {
  it('puts a create() returning the same schema beside every codec schema, at the same indent', () => {
    const out = withCreateFactories(GENERATED, 'typert.host.js')
    expect(out).toContain('          schema: a$schema,\n          create: () => a$schema,\n')
    expect(out).toContain('            schema: b$schema,\n            create: () => b$schema,\n')
    expect(out).toContain('        schema: c$schema,\n        create: () => c$schema,\n')
    expect(out.match(/create: \(\) => /g)).toHaveLength(4)
  })

  it('gives a named schema entry its factory on the same line', () => {
    expect(withCreateFactories(GENERATED, 'typert.host.js'))
      .toContain("    { name: 'Named', schema: a$schema, create: () => a$schema },\n")
  })

  it('leaves a schema definition alone: a quoted zod key named schema is not a codec', () => {
    expect(withCreateFactories(GENERATED, 'typert.host.js')).toContain("  'schema': z.string(),\n})")
  })

  it('keeps the generator header first and says on the next line what was added after it', () => {
    const lines = withCreateFactories(GENERATED, 'typert.host.js').split('\n')
    expect(lines[0]).toBe('/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */')
    expect(lines[1]).toBe(DUAL_CODEC_MARKER)
  })

  it('changes nothing but the added factories and the marker', () => {
    const out = withCreateFactories(GENERATED, 'typert.host.js')
    const undone = out
      .split('\n')
      .filter(line => line !== DUAL_CODEC_MARKER && !/^\s*create: \(\) => \w+\$schema,$/.test(line))
      .join('\n')
      .replace(/, create: \(\) => \w+\$schema \}/g, ' }')
    expect(undone).toBe(GENERATED)
  })

  it('is a no-op on its own output, so a rebuild that did not regenerate cannot double the factories', () => {
    const once = withCreateFactories(GENERATED, 'typert.host.js')
    expect(withCreateFactories(once, 'typert.host.js')).toBe(once)
  })

  it('refuses a strict codec whose schema line it cannot rewrite rather than ship it half converted', () => {
    // An inline expression instead of a named schema constant: the codec
    // exists, the rewrite cannot find its line, and 0.1.7 would reject the
    // manifest. The build must stop and say why.
    const drifted = GENERATED.replace('        schema: c$schema,', '        schema: z.number(),')
    expect(() => withCreateFactories(drifted, 'typert.host.js'))
      .toThrow(/typert\.host\.js: 3 strict codecs but 2 schema lines/)
  })

  it('refuses output that already carries factories: a generator that emits them needs this step rethought', () => {
    const upgraded = GENERATED.replace('        schema: c$schema,', '        create: () => c$schema,')
    expect(() => withCreateFactories(upgraded, 'typert.host.js'))
      .toThrow(/typert\.host\.js: the generator already emits create\(\) factories/)
  })
})

/** One codec a manifest carries and where it sits. */
interface Located { at: string; codec: unknown }

interface InvocationLike {
  id: string
  invocation?: { kind?: string; codec?: unknown }
  parameters?: Array<{ name: string; codec: unknown }>
  result?: unknown
  uplink?: { codec?: unknown }
}

/** Every codec position both harnesses validate: the Context receiver codec,
 * each parameter codec, the result codec and the uplink codec
 * (`requireInvocation` in dsh-typert-loader, `validateInvocation` in
 * dsh-typert-registry). */
function codecsOf(invocations: readonly InvocationLike[]): Located[] {
  const found: Located[] = []
  for (const invocation of invocations) {
    if (invocation.invocation?.codec !== undefined) found.push({ at: `${invocation.id} context`, codec: invocation.invocation.codec })
    for (const parameter of invocation.parameters ?? []) found.push({ at: `${invocation.id} parameter ${parameter.name}`, codec: parameter.codec })
    if (invocation.result !== undefined) found.push({ at: `${invocation.id} result`, codec: invocation.result })
    if (invocation.uplink?.codec !== undefined) found.push({ at: `${invocation.id} uplink`, codec: invocation.uplink.codec })
  }
  return found
}

/** Why one strict codec or named schema would be refused, by either harness
 * generation, or null. 0.1.5-rc.3 (`requireStrictCodec`) demands a zod v4
 * `schema`; 0.1.7-rc.2 (`requireStrictCodec`, `validateCodec`,
 * `validateSchemas`) demands a `create()` factory. The factory must hand back
 * the very same schema, or the two harnesses would validate the wire against
 * different types. */
function refusal(value: unknown): string | null {
  if (typeof value !== 'object' || value === null) return 'not an object'
  const { schema, create } = value as { schema?: unknown; create?: unknown }
  if (typeof schema !== 'object' || schema === null || !('_zod' in schema) || typeof (schema as { parse?: unknown }).parse !== 'function') {
    return 'no zod v4 schema (0.1.5 refuses it)'
  }
  if (typeof create !== 'function') return 'no create() factory (0.1.7 refuses it)'
  if ((create as () => unknown)() !== schema) return 'create() returns a different schema'
  return null
}

function refusalsOf(located: readonly Located[]): string[] {
  const refused: string[] = []
  for (const { at, codec } of located) {
    if ((codec as { mode?: unknown }).mode !== 'strict') continue
    const why = refusal(codec)
    if (why !== null) refused.push(`${at}: ${why}`)
  }
  return refused
}

// The built faces, through the package's own exports: `./typert` is what
// dsh's typert-loader resolves and imports, `./remote` what the client half
// mounts. `pnpm test` builds lib/ first.
describe('the built typert faces', () => {
  const host = TYPERT as unknown as { schemas: Array<{ name: string }>; invocations: InvocationLike[] }
  const remote = TYPERT_REMOTE as unknown as { descriptors: InvocationLike[] }

  it('host face: every codec and named schema loads on both harness generations', () => {
    const located = codecsOf(host.invocations)
    expect(located.length).toBeGreaterThan(0)
    expect(refusalsOf(located)).toEqual([])
    expect(host.schemas.map(schema => refusal(schema)).filter(why => why !== null)).toEqual([])
  })

  it('remote face: every descriptor codec loads on both harness generations', () => {
    const located = codecsOf(remote.descriptors)
    expect(located.length).toBeGreaterThan(0)
    expect(refusalsOf(located)).toEqual([])
  })

  it('the two faces carry the same codecs, so neither half was left out of the rewrite', () => {
    expect(codecsOf(remote.descriptors).map(({ at }) => at)).toEqual(codecsOf(host.invocations).map(({ at }) => at))
  })

  it('the browser bundle inlines the rewritten remote face, one factory per codec', () => {
    // lib/client.js is a CJS closure for the web shell's module loader and
    // cannot be imported here; the factories are counted in its text instead.
    // The client build inlines lib/typert.remote-client.js after the host
    // build rewrote it, so a bundle carrying fewer is a build-order defect.
    const bundle = readFileSync(new URL('../lib/client.js', import.meta.url), 'utf8')
    expect(bundle.match(/create: \(\) => /g)?.length ?? 0).toBe(codecsOf(remote.descriptors).length)
  })
})
